"""
Report Generator for 4C Alert Analysis

Generates markdown reports following the Key Findings template.
Supports two report levels:
- summary: Quick metrics extraction without LLM (low cost)
- full: Complete LLM-generated report (higher cost)
"""

import os
import re
import logging
from typing import Dict, Any, Optional
from datetime import datetime

from .artifact_reader import AlertArtifacts

logger = logging.getLogger(__name__)


class ReportGenerator:
    """
    Generates Key Findings markdown reports for 4C alerts.

    Uses the quantitative-alert.yaml template structure.
    """

    # Default output directory for generated reports
    # Using storage folder (writable volume in Docker)
    DEFAULT_OUTPUT_DIR = "storage/reports"

    def __init__(self, output_dir: Optional[str] = None, llm_provider: str = "openai"):
        """
        Initialize the ReportGenerator.

        Args:
            output_dir: Directory to save generated reports
            llm_provider: LLM provider for full reports ("openai" or "anthropic")
        """
        self.output_dir = output_dir or self.DEFAULT_OUTPUT_DIR
        self.llm_provider = llm_provider

    def generate_report(
        self,
        artifacts: AlertArtifacts,
        content_finding: Any,
        report_level: str = "summary"
    ) -> str:
        """
        Generate a markdown report for an analyzed alert.

        Args:
            artifacts: The alert artifacts
            content_finding: ContentFinding from the analyzer
            report_level: "summary" or "full"

        Returns:
            Markdown string
        """
        if report_level == "full":
            return self._generate_full_report(artifacts, content_finding)
        else:
            return self._generate_summary_report(artifacts, content_finding)

    def _generate_summary_report(
        self,
        artifacts: AlertArtifacts,
        content_finding: Any
    ) -> str:
        """
        Generate a summary report without LLM (quick, low cost).

        Extracts basic metrics and creates a structured report.
        """
        alert_name = content_finding.alert_name
        alert_id = content_finding.alert_id
        module = self._extract_module(alert_name, artifacts)

        # Build the report
        report = []

        # Header
        report.append(f"# {alert_name} Analysis")
        report.append("")
        report.append(f"> **Alert ID:** {alert_id} | **Module:** {module} | **Analysis Date:** {datetime.now().strftime('%B %Y')}")
        report.append("")
        report.append("---")
        report.append("")

        # Key Findings section
        report.append("## Key Findings")
        report.append("")
        report.append("| Metric | Value |")
        report.append("|--------|-------|")
        report.append(f"| Records | {content_finding.total_count:,} |")
        report.append(f"| Total Value | ${content_finding.monetary_amount:,.0f} {content_finding.currency} |")
        report.append(f"| Severity | {content_finding.severity.upper()} |")
        report.append(f"| Risk Score | {content_finding.risk_score}/100 |")
        report.append("")

        # Critical Discovery
        report.append("## Critical Discovery")
        report.append("")
        report.append(f"**{alert_name}:**")
        report.append(f"* {content_finding.what_happened or 'Alert triggered requiring review'}")
        report.append(f"* Focus Area: {content_finding.focus_area.replace('_', ' ').title()}")
        report.append(f"* Risk Level: {content_finding.risk_level}")
        report.append("")

        # Classification
        report.append("## Classification")
        report.append("")
        report.append("| Factor | Assessment |")
        report.append("|--------|------------|")
        report.append(f"| **Focus Area** | {content_finding.focus_area} |")
        report.append(f"| **Severity** | {content_finding.severity} |")
        report.append(f"| **Risk Score** | {content_finding.risk_score}/100 |")
        report.append(f"| **Confidence** | {content_finding.focus_area_confidence:.0%} |")
        report.append("")

        # Recommended Actions
        if content_finding.recommended_actions:
            report.append("## Recommended Actions")
            report.append("")
            for i, action in enumerate(content_finding.recommended_actions[:5], 1):
                report.append(f"{i}. {action}")
            report.append("")

        # Footer
        report.append("---")
        report.append("")
        report.append(f"*Summary report generated by Content Analyzer on {datetime.now().strftime('%Y-%m-%d %H:%M')}*")
        report.append("")

        return "\n".join(report)

    def _generate_full_report(
        self,
        artifacts: AlertArtifacts,
        content_finding: Any
    ) -> str:
        """
        Generate a full report using LLM (comprehensive, follows Key Findings template).

        Falls back to enhanced summary if LLM is unavailable.
        """
        try:
            # Try to use LLM for full report generation
            return self._generate_llm_report(artifacts, content_finding)
        except Exception as e:
            logger.warning(f"LLM report generation failed, falling back to enhanced summary: {e}")
            return self._generate_enhanced_summary_report(artifacts, content_finding)

    def _generate_llm_report(
        self,
        artifacts: AlertArtifacts,
        content_finding: Any
    ) -> str:
        """
        Generate report using LLM following Key Findings template.
        """
        from .llm_classifier import LLMClassifier
        import os

        # Get API key from environment
        if self.llm_provider == "anthropic":
            api_key = os.environ.get("ANTHROPIC_API_KEY")
        else:
            api_key = os.environ.get("OPENAI_API_KEY")

        if not api_key:
            raise ValueError(f"No API key found for {self.llm_provider}")

        classifier = LLMClassifier(
            llm_provider=self.llm_provider,
            api_key=api_key
        )

        # Build prompt for report generation
        prompt = self._build_report_prompt(artifacts, content_finding)

        system_prompt = """You are an expert SAP auditor generating a comprehensive analysis report for a Skywind 4C alert.

Follow this EXACT structure for the report:

## Key Findings
[4-row table: Records, Period, Total Value, Severity]

## Critical Discovery
[Bold heading with entity + amount, 3 bullet points using bullet character]

## Concentration Pattern
[Single table showing concentration, closing observation note]

---
## Business Context
[From Explanation file - what the alert monitors and why it matters]

## Executive Summary
[Alert identity table, execution context, key metrics]

## Risk Assessment
[Classification table with Focus Area, Severity, Risk Score, Fraud Indicator]

## Recommended Actions
[Numbered list of immediate and short-term actions]

## Technical Details
[Source tables, key fields, detection logic summary]

Use these exact formatting rules:
- Use bullet character for bullets, not dashes
- Tables should be clean markdown
- Bold important figures
- Be specific with numbers from the data provided"""

        # Call LLM
        response = classifier._call_llm(system_prompt, prompt)

        # Add header and footer
        alert_name = content_finding.alert_name
        alert_id = content_finding.alert_id
        module = self._extract_module(alert_name, artifacts)

        report = []
        report.append(f"# {alert_name} Analysis")
        report.append("")
        report.append(f"> **Alert ID:** {alert_id} | **Module:** {module} | **Analysis Date:** {datetime.now().strftime('%B %Y')}")
        report.append("")
        report.append("---")
        report.append("")
        report.append(response)
        report.append("")
        report.append("---")
        report.append("")
        report.append(f"*Analysis generated following QUANTITATIVE_ALERT_WORKFLOW.md v1.2 and templates/quantitative-alert.yaml*")
        report.append("")

        return "\n".join(report)

    def _generate_enhanced_summary_report(
        self,
        artifacts: AlertArtifacts,
        content_finding: Any
    ) -> str:
        """
        Generate an enhanced summary report (more detail than basic summary, no LLM).
        """
        alert_name = content_finding.alert_name
        alert_id = content_finding.alert_id
        module = self._extract_module(alert_name, artifacts)

        report = []

        # Header
        report.append(f"# {alert_name} Analysis")
        report.append("")
        report.append(f"> **Alert ID:** {alert_id} | **Module:** {module} | **Analysis Date:** {datetime.now().strftime('%B %Y')}")
        report.append("")
        report.append("---")
        report.append("")

        # Key Findings
        report.append("## Key Findings")
        report.append("")
        report.append("| Metric | Value |")
        report.append("|--------|-------|")
        report.append(f"| Records | {content_finding.total_count:,} |")
        report.append(f"| Total Value | ${content_finding.monetary_amount:,.0f} {content_finding.currency} |")
        report.append(f"| Severity | {content_finding.severity.upper()} |")
        report.append(f"| Risk Score | {content_finding.risk_score}/100 |")
        report.append("")

        # Critical Discovery
        report.append("## Critical Discovery")
        report.append("")
        report.append(f"**{alert_name}:**")
        if content_finding.what_happened:
            report.append(f"* {content_finding.what_happened}")
        if content_finding.business_risk:
            report.append(f"* Business Risk: {content_finding.business_risk}")
        report.append(f"* Classification: {content_finding.focus_area.replace('_', ' ').title()}")
        report.append("")

        # Business Context (from explanation)
        if artifacts.explanation:
            report.append("---")
            report.append("")
            report.append("## Business Context")
            report.append("")
            # Truncate if too long
            explanation = artifacts.explanation[:2000] if len(artifacts.explanation) > 2000 else artifacts.explanation
            report.append(f"> {explanation}")
            report.append("")

        # Executive Summary
        report.append("## Executive Summary")
        report.append("")
        report.append("### Alert Identity")
        report.append("")
        report.append("| Attribute | Value |")
        report.append("|-----------|-------|")
        report.append(f"| **Alert Instance Name** | {alert_name} |")
        report.append(f"| **Alert Instance ID** | {alert_id} |")
        report.append(f"| **Module** | {module} |")
        report.append("")

        # Risk Assessment
        report.append("## Risk Assessment")
        report.append("")
        report.append("### Classification")
        report.append("")
        report.append("| Factor | Assessment | Reasoning |")
        report.append("|--------|------------|-----------|")
        report.append(f"| **Focus Area** | {content_finding.focus_area} | {content_finding.classification_reasoning[:100]}... |")
        report.append(f"| **Severity** | {content_finding.severity} | {content_finding.severity_reasoning[:100] if content_finding.severity_reasoning else 'Based on alert type'}... |")
        report.append(f"| **Risk Score** | {content_finding.risk_score}/100 | Combined qualitative and quantitative assessment |")
        report.append("")

        # Risk Factors
        if content_finding.risk_factors:
            report.append("### Risk Factors")
            report.append("")
            for factor in content_finding.risk_factors[:5]:
                report.append(f"* {factor}")
            report.append("")

        # Recommended Actions
        if content_finding.recommended_actions:
            report.append("## Recommended Actions")
            report.append("")
            report.append("### Immediate")
            report.append("")
            for i, action in enumerate(content_finding.recommended_actions[:3], 1):
                report.append(f"{i}. {action}")
            report.append("")

            if len(content_finding.recommended_actions) > 3:
                report.append("### Short-term")
                report.append("")
                for i, action in enumerate(content_finding.recommended_actions[3:6], 1):
                    report.append(f"{i}. {action}")
                report.append("")

        # Footer
        report.append("---")
        report.append("")
        report.append("## Content Analyzer Output")
        report.append("")
        report.append("```json")
        report.append("{")
        report.append(f'  "alert_id": "{alert_id}",')
        report.append(f'  "alert_name": "{alert_name}",')
        report.append(f'  "module": "{module}",')
        report.append(f'  "classification": {{')
        report.append(f'    "focus_area": "{content_finding.focus_area}",')
        report.append(f'    "severity": "{content_finding.severity}",')
        report.append(f'    "risk_score": {content_finding.risk_score},')
        report.append(f'    "confidence": {content_finding.focus_area_confidence}')
        report.append(f'  }},')
        report.append(f'  "metrics": {{')
        report.append(f'    "total_count": {content_finding.total_count},')
        report.append(f'    "monetary_amount": {content_finding.monetary_amount},')
        report.append(f'    "currency": "{content_finding.currency}"')
        report.append(f'  }}')
        report.append("}")
        report.append("```")
        report.append("")
        report.append("---")
        report.append("")
        report.append(f"*Analysis generated by Content Analyzer v{content_finding.analysis_version} on {datetime.now().strftime('%Y-%m-%d %H:%M')}*")
        report.append("")

        return "\n".join(report)

    def _build_report_prompt(
        self,
        artifacts: AlertArtifacts,
        content_finding: Any
    ) -> str:
        """
        Build the prompt for LLM report generation.
        """
        prompt_parts = []

        prompt_parts.append("Generate a comprehensive analysis report for this Skywind 4C alert.")
        prompt_parts.append("")
        prompt_parts.append("## ALERT DATA")
        prompt_parts.append("")
        prompt_parts.append(f"**Alert Name:** {content_finding.alert_name}")
        prompt_parts.append(f"**Alert ID:** {content_finding.alert_id}")
        prompt_parts.append(f"**Focus Area:** {content_finding.focus_area}")
        prompt_parts.append(f"**Severity:** {content_finding.severity}")
        prompt_parts.append(f"**Risk Score:** {content_finding.risk_score}/100")
        prompt_parts.append(f"**Risk Level:** {content_finding.risk_level}")
        prompt_parts.append("")

        prompt_parts.append("## METRICS")
        prompt_parts.append("")
        prompt_parts.append(f"**Total Records:** {content_finding.total_count:,}")
        prompt_parts.append(f"**Monetary Amount:** ${content_finding.monetary_amount:,.2f} {content_finding.currency}")
        prompt_parts.append(f"**Money Loss Estimate:** ${content_finding.money_loss_estimate:,.2f}")
        prompt_parts.append("")

        if artifacts.explanation:
            prompt_parts.append("## BUSINESS EXPLANATION")
            prompt_parts.append("")
            explanation = artifacts.explanation[:3000] if len(artifacts.explanation) > 3000 else artifacts.explanation
            prompt_parts.append(explanation)
            prompt_parts.append("")

        if artifacts.summary:
            prompt_parts.append("## SUMMARY DATA (First 2000 chars)")
            prompt_parts.append("")
            summary = artifacts.summary[:2000] if len(artifacts.summary) > 2000 else artifacts.summary
            prompt_parts.append(summary)
            prompt_parts.append("")

        if content_finding.risk_factors:
            prompt_parts.append("## RISK FACTORS")
            prompt_parts.append("")
            for factor in content_finding.risk_factors:
                prompt_parts.append(f"- {factor}")
            prompt_parts.append("")

        if content_finding.recommended_actions:
            prompt_parts.append("## RECOMMENDED ACTIONS")
            prompt_parts.append("")
            for action in content_finding.recommended_actions:
                prompt_parts.append(f"- {action}")
            prompt_parts.append("")

        prompt_parts.append("Generate the full markdown report following the Key Findings template exactly.")

        return "\n".join(prompt_parts)

    def _extract_module(self, alert_name: str, artifacts: AlertArtifacts) -> str:
        """
        Extract the SAP module code from alert name or metadata.
        """
        # Common module prefixes in alert names
        module_patterns = {
            "FI": ["financial", "posting", "gl account", "vendor", "balance", "payment"],
            "MM": ["material", "inventory", "purchase", "vendor bank", "goods receipt"],
            "SD": ["sales", "billing", "delivery", "customer", "pricing"],
            "HR": ["employee", "payroll", "personnel"],
            "PP": ["production", "manufacturing"],
            "QM": ["quality", "inspection"]
        }

        alert_lower = alert_name.lower()

        for module, keywords in module_patterns.items():
            if any(kw in alert_lower for kw in keywords):
                return module

        # Check metadata for module hints
        if artifacts.metadata:
            meta_lower = artifacts.metadata.lower()
            for module, keywords in module_patterns.items():
                if any(kw in meta_lower for kw in keywords):
                    return module

        return "GENERAL"

    def save_report(
        self,
        report: str,
        alert_id: str,
        alert_name: str,
        module: str = "GENERAL"
    ) -> str:
        """
        Save the generated report to a markdown file.

        Args:
            report: The markdown content
            alert_id: Alert ID for filename
            alert_name: Alert name for filename
            module: SAP module code

        Returns:
            Path to the saved file
        """
        # Ensure output directory exists
        output_dir = self.output_dir

        # Handle both Docker and local paths
        if not os.path.isabs(output_dir):
            # Try Docker path first
            docker_path = f"/app/{output_dir}"
            if os.path.exists("/app"):
                output_dir = docker_path

        os.makedirs(output_dir, exist_ok=True)

        # Create filename from alert info
        # Clean alert name for filename
        clean_name = re.sub(r'[^\w\s-]', '', alert_name)
        clean_name = re.sub(r'\s+', '_', clean_name)
        clean_name = clean_name[:50]  # Limit length

        filename = f"{module}_{clean_name}_Analysis.md"
        filepath = os.path.join(output_dir, filename)

        # Write the report
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(report)

        logger.info(f"Report saved to: {filepath}")

        return filepath
